version: '3.4'

services:
  hola.api:
    image: ${DOCKER_REGISTRY-}holaapi
    build:
      context: .
      dockerfile: Hola.Api/Dockerfile

 
  dockerservice:
    image: ${DOCKER_REGISTRY-}dockerservice
    build:
      context: .
      dockerfile: DockerService/Dockerfile
    ports:
       - "8011:80"

  apiocelotgetway:
    image: ${DOCKER_REGISTRY-}apiocelotgetway
    build:
      context: .
      dockerfile: APIOcelotGetway/Dockerfile
    ports:
      - "8022:80" 
